# Generated by Django 4.1.3 on 2022-11-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_club_description_club_team_pic_play_isactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='dorm_longhitude',
            new_name='dorm_longitude',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
